version: '3'

services:
  ore-db:
    image: postgres:9
    container_name: ore-db
    environment:
      POSTGRES_PASSWORD: ore
      POSTGRES_USER: ore
      POSTGRES_DB: ore
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  ore-front:
    image: ghcr.io/osmhpi/fuzzed:fe-latest
    container_name: ore-front
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    environment:
      ORE_BACKEND_DAEMON: http://ore-back:8000
      ORE_SERVER_URL: http://ore-front:8000
      ORE_SERVER: ore-front # this adds a host to allowed hosts
      ORE_DB_NAME: ore
      ORE_DB_USER: ore
      ORE_DB_PASSWORD: ore
      ORE_DB_HOST: ore-db
      ORE_SECRET_KEY: change-me-to-something-random-and-very-secret
      ORE_DEV_LOGIN: 1
    ports:
      - 8000:8000
    depends_on:
      - ore-db
      - ore-back

  ore-back:
    image: ghcr.io/osmhpi/fuzzed:be-latest
    container_name: ore-back
    restart: always
    build:
      context: .
      dockerfile: ./backends/Dockerfile

volumes:
  postgres-volume:
