version: '3'

services:
  ore-db-dev:
    image: postgres:9
    container_name: ore-db-dev
    environment:
      POSTGRES_PASSWORD: ore
      POSTGRES_USER: ore
      POSTGRES_DB: ore
    volumes:
      - postgres-volume-dev:/var/lib/postgresql/data

  ore-front-dev:
    image: ghcr.io/osmhpi/fuzzed:fe-latest
    container_name: ore-front-dev
    command:  sh -c '/ore-front/manage.py migrate && ./manage.py runserver 0.0.0.0:8000'
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      ORE_BACKEND_DAEMON: http://ore-back-dev:8000
      ORE_SERVER_URL: http://ore-front-dev:8000
      ORE_SERVER: ore-front-dev
      ORE_DB_NAME: ore
      ORE_DB_USER: ore
      ORE_DB_PASSWORD: ore
      ORE_DB_HOST: ore-db-dev
      DJANGO_CONFIGURATION: Dev
      ORE_SECRET_KEY: 1234
      ORE_DEV_LOGIN: 1
    ports:
      - 8000:8000
    depends_on:
      - ore-db-dev
      - ore-back-dev
    volumes:
      - ./frontend:/ore-front
      - ./common:/ore-common

  ore-back-dev: # to build docker compose exec ore-back-dev cmake . && make
    image: ghcr.io/osmhpi/fuzzed:be-latest
    container_name: ore-back-dev
    build:
      context: .
      dockerfile: ./backends/Dockerfile
    volumes:
      - ./backends:/ore-back
      - ./common:/ore-common
      - /ore-back/lib

volumes:
  postgres-volume-dev:
